<a href="https://colab.research.google.com/github/Rojoniaina-Rasoafarihy/Polarization_detection/blob/main/Datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Mount drive

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import os

base_path = "/content/drive/MyDrive/PathogenFinder2"

folders = [
    "raw_data/pathogenic/ncbi",
    "raw_data/pathogenic/ena",
    "raw_data/pathogenic/patric"

]

for folder in folders:
    os.makedirs(os.path.join(base_path, folder), exist_ok=True)

print("✅ Folder structure created successfully!")

Mounted at /content/drive
✅ Folder structure created successfully!

## NCBI

In [3]:
df_ncbi = pd.read_csv(
    "/content/drive/MyDrive/PathogenFinder2/raw_data/pathogenic/ncbi/isolates.tsv",
    sep="\t",
    on_bad_lines="skip"
)

df_ncbi.shape

/tmp/ipykernel_13583/3007368114.py:1: DtypeWarning: Columns (3,9,11,12,25) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ncbi = pd.read_csv(

(2730498, 26)

In [4]:
df_ncbi.drop_duplicates(inplace=True)

In [5]:
df_ncbi["Isolation type"] = (
    df_ncbi["Isolation type"]
    .fillna("non_clinical")
    .str.lower()
    .apply(lambda x: "clinical" if x == "clinical" else "non_clinical")
)

In [6]:
df_ncbi.columns

Index(['#Organism group', 'Strain', 'Isolate identifiers', 'Serovar',
       'Isolate', 'Create date', 'Location', 'Isolation source',
       'Isolation type', 'Food origin', 'Species TaxID', 'Source type',
       'Virulence genotypes', 'K-mer group', 'Host disease', 'Scientific name',
       'Host', 'SNP cluster', 'SRA Center', 'Min-same', 'Min-diff',
       'BioSample', 'TaxID', 'Assembly', 'AMR genotypes', 'Computed types'],
      dtype='object')

In [7]:
selected_columns = [
    "#Organism group", "Assembly", "TaxID", "Scientific name",
    "Host", "Isolation source", "Isolation type",
    "Host disease", "Location"
]
df_ncbi = df_ncbi[selected_columns]
df_ncbi.head()
save_ncbi = "/content/drive/MyDrive/PathogenFinder2/raw_data/pathogenic/ncbi/ncbi.csv"
df_ncbi.to_csv(save_ncbi, index=False)

In [8]:
df_ncbi.shape
df_ncbi.head()

,#Organism group,Assembly,TaxID,Scientific name,Host,Isolation source,Isolation type,Host disease,Location
0,Listeria monocytogenes,GCA_004104335.1,1639,Listeria monocytogenes,NaN,blood,clinical,NaN,USA
1,Listeria monocytogenes,GCA_004104235.1,1639,Listeria monocytogenes,NaN,NaN,clinical,NaN,USA
2,Listeria monocytogenes,GCA_004358545.1,1639,Listeria monocytogenes,NaN,environmental swab,non_clinical,NaN,USA
3,Listeria monocytogenes,GCA_004358555.1,1639,Listeria monocytogenes,NaN,environmental swab,non_clinical,NaN,USA
4,Listeria monocytogenes,GCA_004104175.1,1639,Listeria monocytogenes,NaN,CSF,clinical,NaN,USA

In [9]:
df_ncbi["Isolation type"].value_counts()

Isolation type
clinical        1789133
non_clinical     941365
Name: count, dtype: int64

### Filter by "pseudomonas aeruginosa" & "blood"

In [10]:
df_ncbi_clinical = df_ncbi[df_ncbi["Isolation type"] == "clinical"]
df_ncbi_clinical.shape

(1789133, 9)

In [11]:
df_ncbi_filter = df_ncbi[ df_ncbi["Scientific name"].str.contains("pseudomonas aeruginosa", case=False, na=False)]
#& df_ncbi["Isolation source"].str.contains("blood", case=False, na=False) & df_ncbi["Host"].str.contains("homo sapiens", case=False, na=False) ]

In [12]:
print(df_ncbi_filter.shape)
df_ncbi_filter.head()

(58217, 9)

,#Organism group,Assembly,TaxID,Scientific name,Host,Isolation source,Isolation type,Host disease,Location
1975399,Pseudomonas aeruginosa,GCA_000006765.1,208964,Pseudomonas aeruginosa PAO1,NaN,NaN,non_clinical,NaN,NaN
1975400,Pseudomonas aeruginosa,GCA_000014625.1,208963,Pseudomonas aeruginosa UCBPP-PA14,NaN,NaN,non_clinical,NaN,NaN
1975401,Pseudomonas aeruginosa,GCA_000026645.1,557722,Pseudomonas aeruginosa LESB58,NaN,NaN,non_clinical,NaN,NaN
1975402,Pseudomonas aeruginosa,GCA_000172395.1,509633,Pseudomonas aeruginosa PAb1,Homo sapiens,clininal isolate from frostbite patient,clinical,NaN,NaN
1975403,Pseudomonas aeruginosa,GCA_000168335.1,388272,Pseudomonas aeruginosa PACS2,NaN,NaN,non_clinical,NaN,NaN

In [13]:
df_ncbi_filter = df_ncbi_filter.drop_duplicates(subset="Assembly")

### Labels of isolation sources

In [14]:
df_ncbi_filter["Isolation source"].value_counts()

Isolation source
sputum                                              5833
lung                                                4515
urine                                               3144
blood                                               2306
clinical                                            1285
                                                    ...
tomato plant                                           1
cystic fibrosis patient with a chronic infection       1
biofilm from an industrial water system                1
air from a glass-crusher air plate                     1
cystic fibrosis chronic infection                      1
Name: count, Length: 1793, dtype: int64

In [15]:
# Get unique values
unique_values = df_ncbi_filter["Isolation source"].dropna().unique()

# Print all
for v in unique_values:
    print(v)

clininal isolate from frostbite patient
cornea of a patient with ulcerative keratitis
gastrointestinal tract
a cystic fibrosis patient
cystic fibrosis chronic infection
soil
air from a glass-crusher air plate
biofilm from an industrial water system
cystic fibrosis patient with a chronic infection
tomato plant
infant with community-acquired diarrhea
sputum sample
blood
sputum of a 14 mo old infant with cystic fibrosis
blood from a hospitalized oncology patient
grown in culture and sent on a short-term space flight
water column
cystic fibrosis isolate
environmental
eye
General Eye
Corneal Scraping
Corneal Scaping
Conjunctiva
Vitreous Fluid
sputum
BAL (mucoid strain)
QC org:ATCC 27853
Lung biopsy
Abd. Woundd
wound
urine
ear
Foot wound
tissue middle turbinate
G-tube site
Groin abscess
shin wound
Abscess (abdominal)
BAL
toenail, subungal debris
Cornea/ocular infection
UTI
Cystic fibrosis
Environmental (water)
Environmental (tomato plant)
Environmental (soil)
patient with pneunomia
Patient (nose)
nose of a patient in the Surgical Intensive Care Unit
t-HCH contaminated soil
Rectal swab
urine from a patient wiht a urinary tract infection
CF isolate
Environmental isolate
sputum (ETT)
Nail bed
compost
river water
cystic fibrosis sputum
marine
genital
right ear
vulvar abscess
Activated sludge of a wastewater treatment plant
Carnivorous Plant Phytotelma
gastric juice from a dolphin kept in captivity in a marine aquarium
water sample from the Indian Ocean
rotten coconut collected in the rain forest
water sample from the Churince water spring
skin
water
fuel tank
decaying wood from a thermal pond
catheter tip
urinary tract infection
respiratory tract infection
itra-abdominal tract infection
lake water
pubic bone
rice rhizosphere soil
blood culture
Portion of Sputum
Surveillance swab
respiratory
Associated Infection
hospital sewage
bronchial alveolar lavage
Westmead Hospital
not collected
sputum sample from patient with non-CF bronchiectasis
Skin wound of burn human patient
hospital
Expectoration
Environment water
Tracheal
Pharma water of cosmetic product
Veterinary
Burn
Nose
throat
CF
Well water
Sore
River
Asite
Tree
drinking water
Clinical non-CF
not known
contaminated soil
endotracheal aspirate
urine cathether
Blood culture of burn human patient
formation water of oilfield produced fluid
cystic fibrosis airways isolate
cystic fibrosis airway
nasopharynx
mid stream urine of a 33 year female patient with a history of genito-urinary Tuberculosis
thigh
chest tube
right knee
bile
Ulu Slim Hot Spring
rectal swab
wound swab
Hospital ward
abdominal
Sputum; Early isolate from VAP patient 1
Sputum; Early isolate from VAP patient 2
Sputum; Late isolate from VAP patient 1
Sputum; Early isolate from VAP patient 4
Sputum; Late isolate from VAP patient 3
Sputum; Late isolate from VAP patient 4
Sputum; Early isolate from VAP patient 3
Sputum; Late isolate from VAP patient 2
Infected wound
wastewater
tracheal aspirate
bloodstream
wound right foot
abscess left buttock
wound right thigh
trachael aspirate
wound neck
bronchoalveolar lavage
bronchial washing
wound r groin
abdominal fluid
trach aspirate
Lindberg collection
induced sputum
murine model
not available
combat injury wound
Airway secretion
Bronchial alveolar lavage
Palma de Mallorca
subsurface water sample
ulcer
unavailable
feces swab
endotracheal tube (ETT) aspirate
foot wound swab
Respiratory Sample
agricultural soil
Bronchial aspirate
Bronchial secretions
mid-stream urine
Aerobic fed-batch lab bioreactor, inoculated from river sediment microbial communities and fed with dextrin/peptone
Aerobic fed-batch lab bioreactor, inoculated from river sediment microbial communities and fed with benzalkonium chloride plus dextrin/peptone
fasciotomy fluid
eye drainage
et tube
infection control
sinus
Cystic fibrosis lung
soil on farm
puddle at Cedarvale Ravine
puddle on farm
soil near pond at Joker's Hill
soil at Joker's Hill
Sawkill stream below waste water outflow
water from pond on golf course
Halobiotic reed
Open Ocean
Green pepper
Zucchini
Green onion
potato
cornea of keratitis patient
cornea from keratitis patient
cornea
tracheal aspiration
adult cystic fibrosis patient
clinical
blueberry-like berries
running water
standing water
Dental unit waterline
Dental instruments washing machine
infected lung
pond water
shower water
pond rock
Lake Michigan water
toilet
shower head
shower drain
reed-like leaf
sink
hospital sink drain
kitchen sink sponge
garden soil
sink drain
standing rain water
detention water
lilypad
Fox River water
algae
horse water trough
sump pump pipe
sump pump pipe water
sand
field soil
soil from horse paddock
stream rock
sink tap
drinking fountain drain
flowers
Chicago River
hosepipe
drainage pipe
horse trough water
ground under water statue
water lily
pipe
water from pipe
bullrush
stream algae
puddle on street
campsite water hose
fountain
fountain water
water statue
sink faucet
Oral swab
environmental swab
Blood culture
Fine needle aspirate
Hospital gel hand wash
pleural fluid
fluid
stem
Abscess
river
sludge
soft tissue
stool
Sacrum
surgical secretion
tracheal secretion
wound swab sample
lung
river sediment
seawater
anal abscess
feces
tracheal secretions
not available: to be reported later
military dog fecal sample
cerebrospinal fluid
orange fruit with canker citrus
Freshwater from Well
hospital effluent
Dagang oil reservoir Sewage
hospital wastewaters
University Hospital of Abidjan-Cocody
Regional hospital of Yamoussoukro
Cystic fibrosis patient
COPD patient
Cystic fibrosis paediatric patient
patient with acute infection
Keratitis
patient with bronchiectasis
Hospital environment
bronchoscopy tissue
Humidifier basin
Rectal
urine clinical sample
Biopsy
Throat (pharynx)
UCC isolate
Endotracheal aspirate
Environment, poultry barn
Water line, poultry barn
heel wound
cystic fibrosis patient throat
leg ulcer
ankle wound
foot wound
leg wound
toe wound
groin wound
foot burn
back wound
cystic fibrosis patient
adult male urine
Intestinal Cancer
abdominal wound
foot ulcer
chest wound
Adult female sputum
Adult male sputum
adult male sputum
sputum of adult cystic fibrosis patient
sputum of child cystic fibrosis patient
infant rectum
urine of adult cystic fibrosis patient
adult male blood
child cystic fibrosis patient, groin
child cystic fibrosis patient, cough swab
pressure sore
burn
Shallow well water
vagina mucosa
egg
organs
Sea water (coastal)
Cenote water
Peritoneal fluid
non cystic fibrosis
Soil/water
respiratory system
Sea water (open ocean)
skin lesion
Clinical non cystic fibrosis
Surgical bandage
catheter
sputum of cystic fibrosis patient
Rice rhizosphere soil
bronchoalveolar lavage of cystic fibrosis patient
throat of cystic fibrosis patient
Bacteraemia patient
clitoris
patient with pneumonia
sputum of adult bronchiectasis patient
uterus
necrotising fasciitis wound
Pool
Patient with keratitis
Hip wound
oral mucosa wound
Child cystic fibrosis patient
Bronchiectasis adult patient
nail pus
pneumonia patient sputum
elbow skin
vaginal mucosa
bronchoalveolar lavage of child cystic fibrosis patient
Respiratory infection
Home
bronchial mucosa, Respiratory infection
Sputum of child cystic fibrosis patient
skin ulcer
Calf burn
leg skin
toe nail
shin ulcer
abdomen skin
central venous catheter
heel ulcer
toe
Post-op wound
Spine pressure sore
female infant ascitic fluid
female infant with Primary Ciliary Dyskinesia
bedside light switch in hospital intensive care unit
bedside rail in hospital intensive care unit
alcohol foam dispenser in hospital intensive care unit
washroom sink in hospital intensive care unit
nursing call button in hospital intensive care unit
individually-maintained laboratory-adapted strain of PAO1 acquired from J. Goldberg, Univ. of Virginia
individually-maintained laboratory-adapted strain of PAO1 acquired from H. Nikaido, Univ. of California, Berkeley
individually-maintained laboratory-adapted strain of PAO1 acquired from C. Manoil, Univ. of Washington
individually-maintained laboratory-adapted strain of PAO1 acquired from A. Prince, Columbia University
individually-maintained laboratory-adapted strain of PAO1 acquired from R. Hancock, Univ. of British Columbia
individually-maintained laboratory-adapted strain of PAO1 acquired from E.P. Greenberg, Univ. of Washington
individually-maintained laboratory-adapted strain of PAO1 acquired from J. Burns, Univ. of Washington
individually-maintained laboratory-adapted strain of PAO1 acquired from D. Ohman, Virginia Commonwealth University
bone
sterile tissue
sterile body fluid
groin
River/sewer
Catheter
Foot
Eye Plate
Maxillary Sinus
nasal mucosa
Chest
milk
Tank water
wound (human)
walker
human hands
burn wound
Tissue fragment
Suture material
Bone fragment
surface water
Secretion swab
Cystic Fibrosis lung sputum
Hospital sink
sandy soil contaminated with hydrocarbons for 50 years
adult male cystic fibrosis patient
not available: not collected
rhizosphere
Wound swab
water bottle, animal room
Pulmonary
an inpatient with liver failure
ATCC Isolate
Water bottle, Animal room
fluid urethra
Abd Wound
Urine, blood, lung
oropharynx, sputum, or bronchoalveolar lavage
Chemostat culture
Duke University Hospital
Dartmouth Hitchcock Medical Center
peritoneal fluid
broncho alveolar lavage
sputum specimen
bile specimen
human gut
crude oil
kidney stone
Tracheal secretions
Urine sample
Abscess sample
Central venous catheter
no data
bronchial secretion
Sputamentum
seroperitoneum
Wound secretion
throat swab
drain
tissue
bal
bronchial lavage
Sputum sample
Mink raising farm
arugula
Sputum-lungs
methanogenic sludge from a potato processing plant
Clinical wastes
Dammam
surgical site
urina
vaginal swab
perineal swab
Oil field soil
Rectal Swab
cystic fibrosis pediatric isolate
landfill
Blowhole
Rectum
bedpan washer
Not collected
artificial saltern
Bronchoalveolar lavage fluid
tertiary hospital, surgery
tertiary hospital, gynecology
Ankle
Urine clean catch
CF sputum
tung meal
other
Wound/Abscess
Tracheal Aspirate/Wash
raw milk
sepsis/hemoculture
Tissue
osteosynthesis material
Secretion
ascites fluid
ETA
Tip (CVL)
Tip (vascath)
Tip (arterial)
Dog ears
tracheal aspirates from patient ventilator
Bones
Wheat Rhizosphere Soil in Dry Farmland
South China Agricultural University maintained the laboratory-adapted strain of PAO1 acquired from E. Peter Greenberg, University of Washington
Integrative Microbiology Research Center, South China Agricultural University (SCAU), Tianhe District, Guangzhou China
sediment
Pus
lumbar puncture
Bronchial aspiration
Tracheal aspiration
Hemoculture
lungs
bacteremia
Tracheal secretion
Bronchial secretion
respiratory sample
human
Surgical intensive care unit
Urology
Medical intensive care unit
Geriatrics 2
Dermatology
Diabetes - Endocrinology
Rehabilitation 1
Geriatrics 1
Trauma unit
Neurosurgery
MICU
Hepatology
Rehabilitation 2
Pneumology
Orthopaedics
Nephrology
Gastroenterology
Vascular surgery
Bronchoalveolar fluid
Biliary fluid
Surgery Wound
URT
Leg
ETT aspirate
endotracheal tube (ETT) or tracheostomy tube
CF respiratory sample
Colonization
Faucet
Floating Countertop
Sink Basin
Tap Water
patient
Bronchial Aspirate
Shunt fluid
frozen meat minced (stuffed cabbage)
Tracheobronchial aspirates
respiratory tract
tracheostomy tube
soft tissue inflammation site
surface biofilm from hospital sink drain
Upper Resp Tract
drainage
broncho-alveolar lavage
trachea
bronchial
protectide specimen brush
Landfill
Pharyngeal secretion
Swab Leg
the sputum of a pneumonia patient
hospital patient
Draining sinus tract from infected LVAD patient
Hospital patients
otopyorrhea
Culture grown in M9 minimal media supplemented with 0.5 % (w/v) glucose
Shower 2
ARJO bathroom
clinical sample
Sacrum Ulcer
Swab-foot
Intra-abdominal infection
Urinary tract infection
Low respiratory tract infection
urine isolate
wound isolate
tracheal aspirate isolate
urine clean catch isolate
fish
ulcer isolate
bronchoalveolar lavage isolate
sputum isolate
foot isolate
blood isolate
abdomen isolate
sputum tracheal aspirate isolate
knee isolate
sputum induced isolate
leg isolate
bronch
scope
CSF
Pleural fluid
Sinus
Catheter Tip
Cell culture
Peritoneal Fluid
Catheter tip
Bronch
Knee joint aspiration
Per urether catheter urine
Fistula drainage
submarine volcano
tracheal
Mahananda river
Ear swab
Hospital Tap Water
Supra pubic catheter urine
Midstream urine
Pericardial fluid
Endotracheal tube
Plastic debris in land/lake environment
pleural cavity
bronchoalveolar lavage (BAL)
tracheotomy tube
skin change
cerebrospinal fluid (CSF)
peritoneal liquor
abdomen
Transurethral Catheter Urine
egg surface
leg
nasopharyngeal swab
DTA
FLUIDS
aspirate
Soil land
domestic wastewater
brain
Surgical wound
Bronchial lavage
Oropharyngeal swab
Rectal swab/stool
Tracheal secretion from tracheostoma
cell culture
deep tracheal aspirate (DTA)
physical
mangrove
Tissue -Foot
Tissue - Abdomen
Tissue - Leg
wound sample
patient with cystic fibrosis
skin, subcutaneous
Abdominal wound
inner ear
swab
Fluid
Neck wound
Blood (whole)
Urine catheter
Heel swab
Tissue ulcer
Urine, clean catch
Ulcer swab
Wound fluid
L axilla burn
Buttock swab
Scraping
Bile fluid
Skin wound
abdominal abscess
soft tissue abscess
bedsore
central venous catheter (CVC)
discharge of the right eye
joint fluid
urethral swab
Drainage
Ascite
ascitic liquid
Swab from Wound
Swab from tracheostomic tube
Pleural Cavity
Nasal Aspirate
Lung sputum
Ward
Intensive Care Unit
Hematology Ward
Soft tissues
oxygen nozzle from reanimation room of Intensive Care Unit
Crude oil well
Sputum specimen
Bacterial isolate specimen
Wound Swab
Pleural fluid specimen
wound (Canis lupus familiaris )
Fluid, Peritoneal
skin secretions
seawater layers
Bronchial Wash
Fluid; abdomen
liver
riverside
Ear (Canis lupus familiaris)
Animal-Swine-Sow (cecal)
Axilla
Long-term care facility
Wound; abdomen
pus
Deep tibia smear
Smear coccyx
Blood through arterial line
Fluid surgical wound
Deep nose smear
Smear
Anal swab
Blood through central line
Wound swab femur
Arterial blood
Deep tissue coccyx
Swab surgical wound
Central venous catheter tip
broncho alveolar lavage fluid
Urinary
liver abscess
Paravertebral fluid
Genital
Joint fluid
Gastrointestinal
URINARY
GASTROINTESTINAL
LINE TIP
GENITAL
tracheal apirate
peritoneal drainage
Petroleum production water
tracheal aspirate/wash
Trachealaspirate
biological sample
sputum from COPD patient
screen
body fluid
laboratory transconjugant
oropharyngeal swabs
nasal swab
derived from the strain Pseudomonas aeruginosa ATCC 27853
Traquel aspirate
peritoneal fluid ascites
bronchial wash
endophyte from plant
polyester fabric recovered from leaf litter
CF lung
Tomato plant
Soi
Pepper plant
Pacific Ocean
Intubated patient
Pneumonia
COPD airways
intestine
Urine, Catheterized
SALMON (SA)
SHRIMP (SH)
Bronchalveolar Lavage
limb
Blood Culture
Blood; left hand
Blood; purple port
Blood; right hand
Pneumonia sputum
Cystic fibrosis sputum
hospital wastewater
O_Room_2_D_Organism_2
Room_2_C_Organism_1
Room_2_E_Organism_3
Room_2_E_Organism_2
Room_2_E_Organism_1
Room_1_C_Organism_1
Room_1_C_Organism_2
Room_1_E_Organism_3
Room_1_E_Organism_2
O_Room_5_D_Organism_2
Room_4_C_Organism_1
Room_4_E_Organism_3
Room_4_C_Organism_3
Room_4_E_Organism_2
O_Room_3_D_Organism_1
O_Room_1_D_Organism_6
O_Room_1_D_Organism_3
Blood_Blood
Room_3_C_Organism_3
O_Room_4_D_Organism_4
Room_4_E_Organism_4
Room_1_Blood
Room_3_C_Organism_1
O_Room_2_D_Organism_3
ST3_Stool_Organism_3
ST3_Stool_Organism_2
ST3_Stool_Organism_1
ST1_Stool_Organism_3
ST1_Stool_Organism_2
ST1_Stool_Organism_1
O_Room_2_D_Organism_1
O_Room_4_D_Organism_3
ST2_Stool_Organism_1
ST4_Stool_Organism_4
ST2_Stool_Organism_3
O_Room_1_D_Organism_2
O_Room_2_C_Organism_1
Room_3_E_Organism_3
Room_3_C_Organism_2
Room_5_C_Organism_1
Room_5_C_Organism_2
Room_5_I_Organism_1
Room_5_E_Organism_4
Room_5_E_Organism_1
Room_5_E_Organism_2
O_Room_5_D_Organism_1
Room_2_C_Organism_2
Room_1_C_Organism_4
Room_1_C_Organism_3
O_Room_6_D_Organism_3
O_Room_6_D_Organism_2
O_Room_3_D_Organism_3
O_Room_3_D_Organism_4
O_Room_3_D_Organism_2
O_Room_4_D_Organism_2
O_Room_4_D_Organism_1
O_Room_5_D_Organism_4
Room_6_E_Organism_1
Room_6_E_Organism_2
sputum lung
trachea fragment
Giant freshwater prawn farm
water sink scupper
collection
water sink surface
oil well produced fluid
The second burn ward of Harbin fifth hospital
phage resistant mutant after challenging wild-type strain PAO1 with bacteriophage AM.P2
skin fragement
Respiratory sample
hip prothesis biopsy
Ventilator Swab External
Ventilator Swab Internal
Endotracheal Aspirate
Pancreatic Tissue
W3C Shower Sink Room
W2E Shower Sink Room
Venous Blood
pulmonary sample
Pus from Wound
Penile Swab
BALs
Sewage sample
extravasate fluid
Respiratory: Endotracheal aspirate
INT: Wound
GU: Urine
INT: Cellulitis/Erysipelas
Respiratory: Bronchoalveolar lavage
INT: Burn
Respiratory: Sputum
CVS: Blood
GI: Small Colon
GI: Abscess
GU: Urinary Bladder
INT: Abscess
INT: Skin Ulcer
GI: Pancreas
Bodily Fluids: Peritoneal
Ear Swab
Soft Tissue/Blood Culture
balf
University Hospital of Nimes
Community water network
University Hospital of Angers
University Hospital of Nantes
University Hospital of Besancon
knee
nd/other
ear infection
wound infection
urinary tract
nd/other, chronic
nd/other, acute
rectal infection
sepsis
pulmonary sample from from cystic fibrosis patient
Burns Care Unit
Neurology
Paranasal sinus
Hospital; patient
Foot swab
Laboratory
endotracheal secretion
Non-CF Bronchiectasis
tissue from heart transplant recipient
Ancestral PA01
Independently evolved isolated clone of PA01 co-cultured with S. maltophilia 8 g/ml treated Synthetic Cystic Fibrosis Media for 24 days
Independently evolved isolated clone of PA01 monocultured in 8 g/ml imipenem treated Synthetic Cystic Fibrosis Media for 24 days
Independently evolved isolated clone of PA01 co-cultured with S. maltophilia 4 g/ml treated Synthetic Cystic Fibrosis Media for 24 days
Independently evolved isolated clone of PA01 monocultured in 4 g/ml imipenem treated Synthetic Cystic Fibrosis Media for 24 days
Independently evolved isolated clone of PA01 co-cultured with S. maltophilia 1 g/ml treated Synthetic Cystic Fibrosis Media for 24 days
Independently evolved isolated clone of PA01 monocultured in 1 g/ml imipenem treated Synthetic Cystic Fibrosis Media for 24 days
Independently evolved isolated clone of PA01 co-cultured with S. maltophilia in Synthetic Cystic Fibrosis Media for 24 days in the absence of imipenem
Independently evolved isolated clone of PA01 monocultured in Synthetic Cystic Fibrosis Media for 24 days in the absence of imipenem
Petroleum contaminated soil
tea garden soil
drainage fluid
CVC
ascitic fluid
COPD
Bacterial Isolate Specimen
rectal
Bronchial Wash (Lavage)
Wound; foot
abscess; foot, right
Not Collected
Catheter Insertion Site
urban runoff waters
Urine, first void
Fluid, bile
cystic fibrosis airways isolate from sputum sample
aspirate tracheal
wound (umbilicus)
oil contaminated environment
Surveillance
rectal swab isolate
swab from tracheostomy tube
swab from purulent wound
groundwater
wound discharge
gut
CF airways
hospital ICU ward
ear swabs
keratitis
cloaca swab
phlegm
Fish pond
Leg, Left
Bronchial
Tissue/leg
tisssue
nose
Not available
cutaneous/wound
auricular
necropsy
ocular
bronchial aspiration
stools
abscess
sink trap
hand washer
tap turn
heel
ventilator
Soft tissue biopsy sample (specimen) [SNOMED:309074002]
wound swab [SNOMED:258531008]
urine [UBERON:0001088]
perianal skin [UBERON:0012336]
respiratory secretion [UBERON:0006538]
blood [UBERON:0000178]
swab (cavity)
unspecified diagnostic sample
swab (wound)
punctate
swab (superficial and non-surgical)
biopsy
secretion
expectorate
perianal swab
Hospital surface within old hospital building
Washing, Bronchial
Domestic environment
Breast
plastic surface of detergent compartment of a washing machine
rubber door sealing of a washing machine
NHS Scotland
Operculum abscess swab (Salt Water Fish\, MISC)
clinical isolate
Recatal swab
Residual water
Cough Swab
Gastric
bronchoalveolar lavage fluid

In [16]:
import pandas as pd


# level 1 and level 2 hierarchical classification
classification = {

    # ---------CLINICAL-------------

    ("Clinical", "Respiratory"): [
        "sputum", "bal", "broncho", "bronchial",
        "trache", "lung", "airway", "respiratory",
        "pharynx", "nasal", "endotracheal",
        "tracheostomy", "lavage", "aspirate",
        "copd", "pneumonia", "ventilator"
    ],

    ("Clinical", "CF_Respiratory"): [
        "cystic fibrosis", "cf sputum",
        "cf respiratory", "cf isolate",
        "cf lung", "cf airway",
        "bronchiectasis"
    ],

    ("Clinical", "Bloodstream"): [
        "blood", "bacteremia",
        "haemoculture", "hemoculture",
        "blood culture", "central line",
        "arterial blood", "venous blood",
        "sepsis"
    ],

    ("Clinical", "Urinary"): [
        "urine", "uti",
        "urinary tract",
        "catheter urine",
        "urinary infection",
        "foley catheter",
        "suprapubic urine",
        "urethra"
    ],

    ("Clinical", "Skin_Soft_Tissue"): [
        "wound", "abscess", "burn",
        "ulcer", "skin", "soft tissue",
        "pus", "lesion", "decubitus",
        "cellulitis", "fasciitis",
        "surgical wound"
    ],

    ("Clinical", "Ocular"): [
        "eye", "cornea", "keratitis",
        "conjunctiva", "vitreous",
        "ocular", "corneal"
    ],

    ("Clinical", "Gastrointestinal"): [
        "stool", "feces", "fecal",
        "rectal", "gut",
        "gastrointestinal", "intestinal",
        "abdomen", "peritoneal",
        "ascitic", "bile",
        "pancreas"
    ],

    ("Clinical", "Ear_Nose_Throat"): [
        "ear", "nose", "throat",
        "sinus", "pharyngeal",
        "nasopharyngeal"
    ],

    ("Clinical", "Reproductive"): [
        "vagina", "vaginal",
        "penis", "uterus",
        "clitoris", "genital",
        "scrotal", "perineal",
        "vulvar"
    ],

    ("Clinical", "Bone_Joint"): [
        "bone", "joint",
        "knee", "hip",
        "tibia", "sacrum",
        "spine", "osteo"
    ],

    ("Clinical", "Medical_Device"): [
        "catheter", "stent",
        "implant", "prosthesis",
        "tube", "line tip",
        "cvc", "cvl"
    ],


    # ---------------ENVIRONMENTAL-------------

    ("Environmental", "Water"): [
        "water", "river", "lake",
        "seawater", "wastewater",
        "ocean", "pond",
        "sink", "drain",
        "tap", "faucet",
        "shower", "spring",
        "well water"
    ],

    ("Environmental", "Soil"): [
        "soil", "sediment",
        "sludge", "rhizosphere",
        "compost", "landfill",
        "mud", "sand"
    ],

    ("Environmental", "Hospital"): [
        "hospital", "icu",
        "ward", "surface",
        "bed rail", "ventilator",
        "room", "hospital sink",
        "medical staff"
    ],

    ("Environmental", "Industrial"): [
        "oil", "fuel tank",
        "wastewater treatment",
        "bioreactor", "petroleum",
        "industrial water",
        "produced fluid"
    ],

    ("Environmental", "Air"): [
        "air", "air plate",
        "air conditioning"
    ],


    # ----------------PLANT---------------

    ("Plant", "Crop"): [
        "tomato", "pepper",
        "lettuce", "onion",
        "potato", "rocket",
        "arugula", "plant",
        "leaf", "root",
        "rhizosphere"
    ],


    # ------------ANIMAL---------------------

    ("Animal", "Domestic"): [
        "dog", "cat",
        "horse", "swine",
        "canine", "feline"
    ],

    ("Animal", "Marine"): [
        "dolphin", "fish",
        "shrimp", "ocean",
        "marine", "turtle"
    ],

    ("Animal", "Bird"): [
        "bird", "cloaca",
        "gallus"
    ],


    # --------------LABORATORY ----------------

    ("Laboratory", "Lab_Strain"): [
        "pao1", "pa14",
        "atcc", "laboratory",
        "lab strain",
        "culture grown",
        "cell culture",
        "chemostat"
    ],

    ("Laboratory", "Experimental"): [
        "mutant", "phage",
        "evolved clone",
        "synthetic cystic fibrosis media",
        "conjugation assay"
    ]
}

In [17]:
# classification function
def classify(text):

    if pd.isna(text):
        return pd.Series(["Unknown", "Unknown"])

    text = str(text).lower()

    for (lvl1, lvl2), keywords in classification.items():

        for kw in keywords:

            if kw in text:
                return pd.Series([lvl1, lvl2])

    return pd.Series(["Unknown", "Unknown"])

In [18]:
df_ncbi_filter[["source_level1", "source_level2"]] = df_ncbi_filter["Isolation source"].apply(classify)

In [19]:
print("\nLEVEL 1 COUNTS\n")
print(df_ncbi_filter["source_level1"].value_counts())

print("\nLEVEL 2 COUNTS\n")
print(df_ncbi_filter["source_level2"].value_counts())

LEVEL 1 COUNTS

source_level1
Clinical         28673
Unknown          17822
Environmental     3369
Laboratory         195
Animal              45
Plant               42
Name: count, dtype: int64

LEVEL 2 COUNTS

source_level2
Unknown             17822
Respiratory         15755
Urinary              3669
Skin_Soft_Tissue     2841
Bloodstream          2593
Hospital             1668
Water                1428
Gastrointestinal     1377
CF_Respiratory        967
Ear_Nose_Throat       917
Ocular                250
Lab_Strain            193
Medical_Device        157
Soil                  134
Air                   123
Bone_Joint             99
Reproductive           48
Crop                   42
Industrial             16
Domestic               16
Marine                 15
Bird                   14
Experimental            2
Name: count, dtype: int64

In [51]:
# create final labeled dataframe
df_labels = df_ncbi_filter[
    [
        "Assembly",
        "Isolation source",
        "source_level1",
        "source_level2"
    ]
].copy()

# preview
df_labels.head()

,Assembly,Isolation source,source_level1,source_level2
1975399,GCA_000006765.1,NaN,Unknown,Unknown
1975400,GCA_000014625.1,NaN,Unknown,Unknown
1975401,GCA_000026645.1,NaN,Unknown,Unknown
1975402,GCA_000172395.1,clininal isolate from frostbite patient,Unknown,Unknown
1975403,GCA_000168335.1,NaN,Unknown,Unknown

In [52]:
# save as CSV
df_labels.to_csv(
    "isolation_source_labels.csv",
    index=False
)

print("CSV saved!")

CSV saved!

## ENA

In [24]:
df_ena = pd.read_csv(
    "/content/drive/MyDrive/PathogenFinder2/raw_data/pathogenic/ena/results_assembly_1.tsv",
    sep="\t"
)

/tmp/ipykernel_13583/2885628364.py:1: DtypeWarning: Columns (1,3,5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ena = pd.read_csv(

In [25]:
df_ena.shape

(4179286, 14)

In [26]:
df_ena.drop_duplicates(inplace=True)

In [27]:
df_ena.head()

,sample_accession,host,assembly_level,sequence_accession,status,assembly_quality,strain,assembly_accession,isolation_source,host_scientific_name,tax_id,host_tax_id,scientific_name,accession
0,SAMN03197995,Homo sapiens,scaffold,NaN,public,NaN,784_LRHA,GCA_001067335,missing,Homo sapiens,47715,9606.0,Lacticaseibacillus rhamnosus,GCA_001067335
1,SAMN03198026,Homo sapiens,scaffold,NaN,public,NaN,812_SBOY,GCA_001067425,missing,Homo sapiens,562,9606.0,Escherichia coli,GCA_001067425
2,SAMN03198028,Homo sapiens,scaffold,NaN,public,NaN,814_SAUR,GCA_001067445,missing,Homo sapiens,1280,9606.0,Staphylococcus aureus,GCA_001067445
3,SAMN03198124,Homo sapiens,contig,NaN,public,NaN,914_NLAC,GCA_001067635,missing,Homo sapiens,267212,9606.0,Neisseria bacilliformis,GCA_001067635
4,SAMN03198132,Homo sapiens,contig,NaN,public,NaN,919_NLAC,GCA_001067655,missing,Homo sapiens,486,9606.0,Neisseria lactamica,GCA_001067655

In [28]:
df_ena["host"].value_counts()

host
Homo sapiens                          1041727
missing                                141706
Sus scrofa                              26784
Gallus gallus                           26221
Bos taurus                              19963
                                       ...
Alnus cremastogyne                          1
Rhododendron simsii                         1
Gleditsia sinensis                          1
Hypervirulent Aeromonas hydrophila          1
Eugeissona                                  1
Name: count, Length: 11317, dtype: int64

In [29]:
df_ena["Isolation type"] = df_ena["host"].apply(
    lambda x: "clinical" if str(x).strip().lower() == "homo sapiens" else "non_clinical"
)

In [30]:
df_ena.columns

Index(['sample_accession', 'host', 'assembly_level', 'sequence_accession',
       'status', 'assembly_quality', 'strain', 'assembly_accession',
       'isolation_source', 'host_scientific_name', 'tax_id', 'host_tax_id',
       'scientific_name', 'accession', 'Isolation type'],
      dtype='object')

In [31]:
selected_columns = [
    "tax_id", "scientific_name", "host_tax_id", "host",
    "host_scientific_name", "isolation_source", "assembly_accession",
    "assembly_level", "status","Isolation type"
]
df_ena = df_ena[selected_columns]
df_ena.head()

save_ena = "/content/drive/MyDrive/PathogenFinder2/raw_data/pathogenic/ncbi/ena.csv"
df_ena.to_csv(save_ena, index=False)

In [32]:
print(df_ena.shape)
df_ena.head()

(4115036, 10)

,tax_id,scientific_name,host_tax_id,host,host_scientific_name,isolation_source,assembly_accession,assembly_level,status,Isolation type
0,47715,Lacticaseibacillus rhamnosus,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067335,scaffold,public,clinical
1,562,Escherichia coli,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067425,scaffold,public,clinical
2,1280,Staphylococcus aureus,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067445,scaffold,public,clinical
3,267212,Neisseria bacilliformis,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067635,contig,public,clinical
4,486,Neisseria lactamica,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067655,contig,public,clinical

In [33]:
df_ena_filter = df_ena[ df_ena["scientific_name"].str.contains("pseudomonas aeruginosa", case=False, na=False)]
#& df_ena["isolation_source"].str.contains("blood", case=False, na=False) & df_ena["host"].str.contains("homo sapiens", case=False, na=False) ]
print(df_ena_filter.shape)
df_ena_filter.head()

(51654, 10)

,tax_id,scientific_name,host_tax_id,host,host_scientific_name,isolation_source,assembly_accession,assembly_level,status,Isolation type
7,287,Pseudomonas aeruginosa,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067725,contig,public,clinical
10,287,Pseudomonas aeruginosa,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067795,contig,public,clinical
15,287,Pseudomonas aeruginosa,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001067965,contig,public,clinical
18,287,Pseudomonas aeruginosa,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001068115,contig,public,clinical
336,287,Pseudomonas aeruginosa,9606.0,Homo sapiens,Homo sapiens,missing,GCA_001076225,scaffold,public,clinical

In [34]:
df_ena_filter["scientific_name"].value_counts()

scientific_name
Pseudomonas aeruginosa         51209
Pseudomonas aeruginosa PAO1       24
Pseudomonas aeruginosa 7D9A       18
Pseudomonas aeruginosa PA14       15
Pseudomonas aeruginosa 1BAE       14
                               ...
Pseudomonas aeruginosa BL18        1
Pseudomonas aeruginosa BL19        1
Pseudomonas aeruginosa BL20        1
Pseudomonas aeruginosa BL21        1
Pseudomonas aeruginosa BL13        1
Name: count, Length: 302, dtype: int64

In [35]:
df_ena_filter["assembly_accession"].value_counts()

assembly_accession
GCA_021644425    4
GCA_000215795    3
GCA_002812925    3
GCA_000473745    3
GCA_031480695    3
                ..
GCA_037117315    1
GCA_037117335    1
GCA_037117355    1
GCA_037117365    1
GCA_037104505    1
Name: count, Length: 51275, dtype: int64

In [36]:
df_ena_filter = df_ena_filter.drop_duplicates(subset="assembly_accession")

In [37]:
print(df_ena_filter.shape)

(51275, 10)

## PATRIC

In [38]:
df_patric = pd.read_csv(
    "/content/drive/MyDrive/PathogenFinder2/raw_data/pathogenic/patric/BVBRC_genome.csv"
)

df_patric.shape

/tmp/ipykernel_13583/3900280399.py:1: DtypeWarning: Columns (16,17,18,21,31,32,33,34,37,38,69,76,80,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df_patric = pd.read_csv(

(336046, 90)

In [39]:
df_patric.drop_duplicates(inplace=True)

In [40]:
df_patric.head()

,Genome ID,Genome Name,Other Names,NCBI Taxon ID,Taxon Lineage IDs,Taxon Lineage Names,Superkingdom,Kingdom,Phylum,Class,...,Host Age,Host Health,Host Group,Lab Host,Passage,Other Clinical,Additional Metadata,Comments,Date Inserted,Date Modified
0,100053.40,Leptospira alexanderi strain 56650,NaN,100053,131567;2;3379134;203691;203692;1643688;170;171...,cellular organisms;Bacteria;Pseudomonadati;Spi...,Bacteria,Pseudomonadati,Spirochaetota,Spirochaetia,...,NaN,Leptospirosis,Human,NaN,NaN,NaN,collected_by:Jincai Qin,Comparative genomics analysis of 102 Leptospir...,2017-03-20T08:35:16.825Z,2017-03-20T08:35:16.825Z
1,100053.60,Leptospira alexanderi strain 56640,NaN,100053,131567;2;3379134;203691;203692;1643688;170;171...,cellular organisms;Bacteria;Pseudomonadati;Spi...,Bacteria,Pseudomonadati,Spirochaetota,Spirochaetia,...,NaN,Leptospirosis,Human,NaN,NaN,NaN,collected_by:Jincai Qin,Comparative genomics analysis of 102 Leptospir...,2017-03-20T08:35:25.103Z,2017-03-20T08:35:25.103Z
2,100053.80,Leptospira alexanderi strain 56659,NaN,100053,131567;2;3379134;203691;203692;1643688;170;171...,cellular organisms;Bacteria;Pseudomonadati;Spi...,Bacteria,Pseudomonadati,Spirochaetota,Spirochaetia,...,NaN,Leptospirosis,Human,NaN,NaN,NaN,collected_by:Jincai Qin,Comparative genomics analysis of 102 Leptospir...,2017-03-20T08:36:40.695Z,2017-03-20T08:36:40.695Z
3,1000561.30,Pseudomonas aeruginosa AES-1R,NaN,1000561,131567;2;3379134;1224;1236;72274;135621;286;13...,cellular organisms;Bacteria;Pseudomonadati;Pse...,Bacteria,Pseudomonadati,Pseudomonadota,Gammaproteobacteria,...,infant,cystic fibrosis,Human,NaN,NaN,NaN,NaN,Pseudomonas aeruginosa AES-1R was isolated fro...,2014-12-08T22:12:36.342Z,2015-03-16T03:17:09.594Z
4,1000568.21,Megasphaera lornae C043_04,NaN,1000568,131567;2;1783272;1239;909932;1843489;31977;906...,cellular organisms;Bacteria;Bacillati;Bacillot...,Bacteria,Bacillati,Bacillota,Negativicutes,...,NaN,NaN,Human,NaN,NaN,host_subject_id:C043,sample_type:metagenomic assembly,NaN,2025-02-03T22:24:35.692Z,2025-02-03T22:24:35.692Z

In [41]:
df_patric.columns

Index(['Genome ID', 'Genome Name', 'Other Names', 'NCBI Taxon ID',
       'Taxon Lineage IDs', 'Taxon Lineage Names', 'Superkingdom', 'Kingdom',
       'Phylum', 'Class', 'Order', 'Family', 'Genus', 'Species',
       'Genome Status', 'Strain', 'Serovar', 'Biovar', 'Pathovar', 'MLST',
       'Segment', 'Subtype', 'H_type', 'N_type', 'H1 Clade Global',
       'H1 Clade US', 'H5 Clade', 'pH1N1-like', 'Lineage', 'Clade', 'Subclade',
       'Other Typing', 'Culture Collection', 'Type Strain', 'Reference',
       'Genome Quality', 'Completion Date', 'Publication', 'Authors',
       'BioProject Accession', 'BioSample Accession', 'Assembly Accession',
       'SRA Accession', 'GenBank Accessions', 'Sequencing Center',
       'Sequencing Status', 'Sequencing Platform', 'Sequencing Depth',
       'Assembly Method', 'Chromosome', 'Plasmids', 'Contigs', 'Size',
       'GC Content', 'Contig L50', 'Contig N50', 'TRNA', 'RRNA', 'Mat Peptide',
       'CDS', 'Coarse Consistency', 'Fine Consistency', 'CheckM Contamination',
       'CheckM Completeness', 'Genome Quality Flags', 'Isolation Source',
       'Isolation Comments', 'Collection Date', 'Collection Year', 'Season',
       'Isolation Country', 'State/Province', 'County', 'City',
       'Geographic Group', 'Geographic Location', 'Other Environmental',
       'Host Name', 'Host Common Name', 'Host Sex', 'Host Age', 'Host Health',
       'Host Group', 'Lab Host', 'Passage', 'Other Clinical',
       'Additional Metadata', 'Comments', 'Date Inserted', 'Date Modified'],
      dtype='object')

In [42]:
selected_columns = [
    "Genome ID", "NCBI Taxon ID", "Species", "Host Name",
    "Host Health", "Isolation Source","Isolation Country",
"Comments", "Other Clinical", "Isolation Comments"
]
df_patric = df_patric[selected_columns]
df_patric.head()
save_patric = "/content/drive/MyDrive/PathogenFinder2/raw_data/pathogenic/ncbi/patric.csv"
df_patric.to_csv(save_patric, index=False)

In [43]:
df_patric_filter = df_patric[ df_patric["Species"].str.contains("pseudomonas aeruginosa", case=False, na=False)]
#& df_patric["Isolation Source"].str.contains("blood", case=False, na=False) ]
print(df_patric_filter.shape)
df_patric_filter.head()

(11758, 10)

,Genome ID,NCBI Taxon ID,Species,Host Name,Host Health,Isolation Source,Isolation Country,Comments,Other Clinical,Isolation Comments
3,1000561.30,1000561,Pseudomonas aeruginosa,"Human, Homo sapiens",cystic fibrosis,the sputum of a 14 month old infant with cysti...,NaN,Pseudomonas aeruginosa AES-1R was isolated fro...,NaN,isolated from the sputum of a 14 month old inf...
1570,1078464.30,1078464,Pseudomonas aeruginosa,"Human, Homo sapiens",NaN,Japan,Japan,MDR P. aeruginosa NCGM1179 was isolated from t...,NaN,MDR P. aeruginosa NCGM1179 was isolated from t...
1585,1081927.11,1081927,Pseudomonas aeruginosa,Homo sapiens,NaN,NaN,NaN,NaN,NaN,NaN
1586,1081927.12,1081927,Pseudomonas aeruginosa,Homo sapiens,NaN,sputum,NaN,NaN,NaN,NaN
1587,1081927.40,1081927,Pseudomonas aeruginosa,"Human, Homo sapiens",NaN,sputum,NaN,Whole-genome sequencing of toxogenic clinical ...,NaN,NaN

In [44]:
df_patric['Other Clinical'].unique()

array([nan, 'host_subject_id:C043', 'host_subject_id:14-2', ...,
       'host_subject_id:Patient 15',
       'host_description:CF patient that regularly attended adult CF clinics',
       'host_description:Pediatric pacient;host_disease_outcome:Death'],
      dtype=object)

In [45]:
df_patric["Isolation type"] = "clinical"

In [46]:
df_patric.head()

,Genome ID,NCBI Taxon ID,Species,Host Name,Host Health,Isolation Source,Isolation Country,Comments,Other Clinical,Isolation Comments,Isolation type
0,100053.40,100053,Leptospira alexanderi,"Human, Homo sapiens",Leptospirosis,NaN,China,Comparative genomics analysis of 102 Leptospir...,NaN,NaN,clinical
1,100053.60,100053,Leptospira alexanderi,"Human, Homo sapiens",Leptospirosis,NaN,China,Comparative genomics analysis of 102 Leptospir...,NaN,NaN,clinical
2,100053.80,100053,Leptospira alexanderi,"Human, Homo sapiens",Leptospirosis,NaN,China,Comparative genomics analysis of 102 Leptospir...,NaN,NaN,clinical
3,1000561.30,1000561,Pseudomonas aeruginosa,"Human, Homo sapiens",cystic fibrosis,the sputum of a 14 month old infant with cysti...,NaN,Pseudomonas aeruginosa AES-1R was isolated fro...,NaN,isolated from the sputum of a 14 month old inf...,clinical
4,1000568.21,1000568,Megasphaera lornae,Homo sapiens,NaN,maternal stool,USA,NaN,host_subject_id:C043,NaN,clinical

In [47]:
df_patric_filter["Species"].value_counts()

Species
Pseudomonas aeruginosa    11758
Name: count, dtype: int64

In [48]:
df_patric_filter = df_patric_filter.drop_duplicates(subset="Genome ID")

In [49]:
print(df_patric_filter.shape)

(11461, 10)

In [50]:
df_patric_filter["Genome ID"].to_csv("genome_ids.txt", index=False, header=False)